# lr_to_stereo.sh
# merge left and right images made by <pbrt_independant_stereo.sh> into a single stereo image
# use .png images
# N is the number independant couples of images generated by  <pbrt_independant_stereo.sh>

# syntax: bash lt_to_stereo.sh [name] [N]

#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source /home/qhuan/script/pbrt_path.sh
cd $scripts

N=$2
filename="${1%.*}"


cd /mnt/data/qhuan/stereoDataBase
mkdir ${filename}_stereo

#merge
for (( c=0; c<N; c++ ))
do

   echo "merging image $c"
   $pngcat2 ${output}/StereoDataBase_merged_png/p3d_${filename}-left/p3d_${filename}-left_1_${c}.png ${output}/StereoDataBase_merged_png/p3d_${filename}-right/p3d_${filename}-right_1_${c}.png /mnt/data/qhuan/stereoDataBase/${filename}_stereo/${filename}_stereo_${c}.png

done

echo --------------------
echo "Done"
echo --------------------
